pipeline {
    agent any
    tools {
        maven 'maven3'
        jdk 'jdk8'
    }
    triggers {
        cron('H * * * *')
        pollSCM('* * * * *')
    }
    environment {
        MVN_SETTINGS = credentials('maven-settings')
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -s $MVN_SETTINGS -B -DskipTests clean package'
            }
        }
        stage('Deploy') {
            when {
                branch 'main'
            }
            steps {
                sh 'mvn -s $MVN_SETTINGS -DskipTests deploy'
            }
        }
    }
}