pipeline {
    agent any
    tools {
        maven 'maven3'
        jdk 'jdk8'
    }
    triggers {
        cron('H * * * *')
        pollSCM('* * * * *')
        upstream(
            upstreamProjects: "isa-devops-2021-team-f-account-server,isa-devops-2021-team-f-shopping-server,isa-devops-2021-team-f-payment-server,isa-devops-2021-team-f-resort-server,isa-devops-2021-team-f-statistics-server, isa-devops-2021-team-f-monitoring-server, isa-devops-2021-team-f-notification-server",
            threshold: hudson.model.Result.SUCCESS
        )
    }
    environment {
        MVN_SETTINGS = credentials('maven-settings')
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -s $MVN_SETTINGS -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -s $MVN_SETTINGS test'
            }
        }
        stage('Deploy') {
            when {
                branch 'main'
            }
            steps {
                sh 'mvn -s $MVN_SETTINGS -DskipTests deploy'
            }
        }
    }
}
